apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registerapp-java
  template:
    metadata:
      labels:
        app: registerapp-java
    spec:
      containers:
        - name: registerapp-java
          image: ajeevan/registerapp-java-pipeline:1.0.0-11
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
